# Generated by Django 3.2.9 on 2021-11-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('review_text', models.CharField(max_length=200, verbose_name='Текст отзыва')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.animal')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
